<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 D:\DEV\threlte_project\shibuya\static\models\box_ex.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    onClick,
    isFocused = false,
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    onClick?: () => void
    isFocused?: boolean
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/box_ex.glb')
  
  // Generate random color
  const randomColor = () => `#${Math.floor(Math.random()*16777215).toString(16).padStart(6, '0')}`
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
  onclick={onClick}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Material}
      onclick={onClick}
    >
      <T.MeshStandardMaterial 
        color={randomColor()} 
        emissive={isFocused ? '#ff0000' : '#000000'}
        emissiveIntensity={isFocused ? 0.3 : 0}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
